#include "hash.h"
#include <math.h>


// from the official standard : 
// " Each algorithm can be described in two stages: preprocessing and hash computation "

// "Preprocessing involves padding a message, parsing the padded message into m-bit blocks, and
// setting initialization values to be used in the hash computation. "


// "The hash computation generates
// a message schedule from the padded message and uses that schedule, along with functions,
// constants, and word operations to iteratively generate a series of hash values. The final hash
// value generated by the hash computation is used to determine the message digest"


static uint32_t bytes_to_be(uchar_t input[4]) {
    return (uint32_t) ((input[0] << 24) | (input[1] << 16) | (input[2] << 8) | input[3]) ;
}

// ????
static void be_to_bytes(uint32_t num , uchar_t input[4]) {
    input[0] = (num & 0xff000000 ) >> 24 ;
    input[1] = (num & 0x00ff0000 ) >> 16 ;
    input[2] = (num & 0x0000ff00 ) >> 8 ;
    input[3] = (num & 0x000000ff )  ;
}



static uint32_t rotl_32bit(uint32_t a , uint32_t times) {
    times %= 32 ;

    if (!times)
        return a ;


    return ((a << times) | (a >> (32 - times))) ;
}


static uint32_t rotr_32bit(uint32_t a , uint32_t times) {
    times %= 32 ;
    
    if (!times)
    return a ;
    
    
    return ((a >> times) | (a << (32 - times))) ;
}


static uint32_t shr_32bit(uint32_t a , uint32_t times) {
    return a >> times ;
}

static uint32_t shl_32bit(uint32_t a , uint32_t times) {
    return a << times ;
}


static void Ch_sha256(uchar_t *x , uchar_t *y , uchar_t *z , uchar_t *result) {

    uchar_t temp1[4] ;
    for (int i = 0; i < 4; i++)
    {
        temp1[i] = x[i] & y[i] ;
    }

    uchar_t temp2[4] ;
    for (int i = 0; i < 4; i++)
    {
        temp2[i] = (~x[i]) & z[i] ;
    }

    for (int i = 0; i < 4; i++)
    {
        result[i] = temp1[i] ^ temp2[i] ;
    }

}


static void Maj_sha256(uchar_t *x , uchar_t *y , uchar_t *z , uchar_t *result) {

    uchar_t temp1[4] ;
    for (int i = 0; i < 4; i++)
    {
        temp1[i] = x[i] & y[i] ;
    }

    uchar_t temp2[4] ;
    for (int i = 0; i < 4; i++)
    {
        temp2[i] = x[i] & z[i] ;
    }
    
    uchar_t temp3[4] ;

    for (int i = 0; i < 4; i++)
    {
        temp3[i] = y[i] & z[i] ;
    }


    for (int i = 0; i < 4; i++)
    {
        result[i] = temp1[i] ^ temp2[i] ^ temp3[i] ;
    }


}



static uint32_t Sum0_256_sha256(uint32_t num) {
    return rotr_32bit(num , 2) ^ rotr_32bit(num , 13) ^ rotr_32bit(num , 22)   ; 
}


static uint32_t Sum1_256_sha256(uint32_t num) {
    return rotr_32bit(num , 6) ^ rotr_32bit(num , 11) ^ rotr_32bit(num , 25)   ; 
}


static uint32_t Sigma0_256_sha256(uint32_t num) {
    return rotr_32bit(num , 7) ^ rotr_32bit(num , 18) ^ shr_32bit(num , 3)   ; 
}

static uint32_t Sigma1_256_sha256(uint32_t num) {
    return rotr_32bit(num , 17) ^ rotr_32bit(num , 19) ^ shr_32bit(num , 10)   ; 
}

// maybe there is a better way to do this shit :
static void init_Hash_Values(uchar_t H[8*4]) {
    const int PRIMES_64[64] = {
        2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 
        31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 
        73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 
        127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 
        179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 
        233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 
        283, 293, 307, 311
    };

    int b ;
    long double d ;  
    int j = 0 ;
    for (int i = 0; i < 8*4; i+=4)
    {
        d = sqrt(PRIMES_64[j]) * 4294967296 ;
        b = (uint32_t) d ;
        // printf(" b = %u \t %x  \n" , b , b) ; 
        be_to_bytes(b , H + i) ;
        j++ ;  

    }


}



static void init_K(uchar_t K[64*4]) {
    const int PRIMES_64[64] = {
        2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 
        31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 
        73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 
        127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 
        179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 
        233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 
        283, 293, 307, 311
    };

    int b ;
    long double d ;  
    int j = 0 ; 
    for (int i = 0; i < 64*4; i+=4)
    {
        d = cbrt(PRIMES_64[j]) * 4294967296 ;
        b = (uint32_t) d ;
        // printf(" b = %u \t %x  \n" , b , b) ; 
        be_to_bytes(b , K + i) ; 
        j++ ; 
    }
        
}




uchar_t* sha256_padding(uchar_t M[] , uint64_t b , uint64_t *output_length ) {
    // b number of bits ?
    // the specification says that it needs not be to be mulytiply of 8 ??? (pretty much weird)
    *output_length = b +64 +  (512 - ((b+64)  % 512)) ;

    uchar_t *output = malloc(*output_length * sizeof(uchar_t)  ) ;
    if (b % 8 == 0)
    {
        memcpy(output , M  , sizeof(uchar_t)* b / 8) ;
        // 512 / 8 = 64
        // this contains length % 64 bytes
        uint32_t temp = (b / 8) % 64  ;
        uint32_t index =  b / 8 ;

        output[index] = 0x80 ;
        index++ ;
        temp++ ;

        // 448 / 8 = 56
        while (temp % 64 != 56)
        {
            output[index] = 0x00 ;
            index++ ;
            temp++ ;
        }
        // append length now ... .???????????????????????

        
        #if 0
        output[index]   =   (b & 0x00000000000000ff ) ; 
        output[index+1] =   (b & 0x000000000000ff00 ) >> 8 ; 
        output[index+2] =   (b & 0x0000000000ff0000 ) >> 16; 
        output[index+3] =   (b & 0x00000000ff000000 ) >> 24; 
        index += 4 ; 
        
        output[index]   =   (b & 0x000000ff00000000 ) >> 32; 
        output[index+1] =   (b & 0x0000ff0000000000 ) >> 40; 
        output[index+2] =   (b & 0x00ff000000000000 ) >> 48; 
        output[index+3] =   (b & 0xff00000000000000 ) >> 56; 
        index += 4 ; 
        #else

            output[index] =   (b & 0xff00000000000000 ) >> 56 ; 
            output[index+1] = (b & 0x00ff000000000000 ) >> 48 ; 
            output[index+2] = (b & 0x0000ff0000000000 ) >> 40; 
            output[index+3] = (b & 0x000000ff00000000 ) >> 32; 
        
            index += 4 ; 
        
            output[index] =   (b & 0x00000000ff000000 ) >> 24 ; 
            output[index+1] = (b & 0x0000000000ff0000 ) >> 16 ; 
            output[index+2] = (b & 0x000000000000ff00 ) >> 8; 
            output[index+3] = (b & 0x00000000000000ff ); 
        
        
            index += 4 ; 
        #endif


         printf("calculated output length : %ld \n" , *output_length ) ;
         printf("calculated output length/8 : %ld \n" , *output_length / 8) ;
        printf("index : %u \n" , index) ;
        *output_length = index *8; 
        assert(index == *output_length / 8 && "these 2 should be equal ???") ;
    } else {
        // ????????????????????????
        // TODO : handle this case too ...
        // ????????????????????????
        printf("not implemented (my pc works with only 8 bits :( \n")  ;
        exit(12) ;
    }

    return output ;

}



void sha256_hash(const uchar_t* data, size_t len, uchar_t digest[32]) {
    
    uchar_t H[8*4] ; 
    uchar_t W[64*4] ; 
    uchar_t K[64*4] ; 

    init_K(K) ;
    init_Hash_Values(H) ;


    uint64_t output_length  ; 
    uchar_t *input_padded = sha256_padding(data , 8*len , &output_length) ; 
    output_length /= 8 ; 

    uint32_t a , b , c , d , e ,f , g, h ;

    printf("N =  %d\n" , output_length) ; 
    printf("here you go looping from 0 to N/(16*4)-1 : %d\n" , output_length/(16*4)-1) ; 
    for (size_t i = 0; i <= output_length/(16*4)-1; i++)
    {

        // memcpy(X  , M + (i* 16 *4 ) , sizeof(uchar_t) * 4*16) ;
        for (size_t t = 0; t < 16; t++)
        {
            memcpy(W + (t*4) , input_padded + (t*4 ) , sizeof(uchar_t ) * 4 * 1) ; 
            // be_to_bytes(result , W + t*4 ) ;
        }
        for (size_t t = 16; t < 64; t++)
        {
            uint32_t result = Sigma1_256_sha256(bytes_to_be(W + (t -2)*4)) + bytes_to_be(W + (t -7)*4) + Sigma0_256_sha256(bytes_to_be(W + (t -15)*4)) + bytes_to_be(W + (t -16)*4)    ; 
            be_to_bytes(result , W + t*4 ) ;
        }
        
        a = bytes_to_be(H + 0*4) ; 
        b = bytes_to_be(H + 1*4) ; 
        c = bytes_to_be(H + 2*4) ; 
        d = bytes_to_be(H + 3*4) ; 
        e = bytes_to_be(H + 4*4) ; 
        f = bytes_to_be(H + 5*4) ; 
        g = bytes_to_be(H + 6*4) ; 
        h = bytes_to_be(H + 7*4) ; 
        
        
        
        for (size_t t = 0; t < 64; t++)
        {

            uchar_t a_bytes[4] ;
            uchar_t b_bytes[4] ;
            uchar_t c_bytes[4] ;
            uchar_t e_bytes[4] ;
            uchar_t f_bytes[4] ;
            uchar_t g_bytes[4] ;
            uchar_t result[4] ;
            be_to_bytes(e , e_bytes) ; 
            be_to_bytes(f , f_bytes) ; 
            be_to_bytes(g , g_bytes) ; 
            
            Ch_sha256(e_bytes , f_bytes , g_bytes , result) ;
            
            uint32_t T1 = h + Sum1_256_sha256(e) + bytes_to_be(result) + bytes_to_be(K + t*4) + bytes_to_be(W + t*4)   ;  
            
            be_to_bytes(a , a_bytes) ; 
            be_to_bytes(b , b_bytes) ; 
            be_to_bytes(c , c_bytes) ; 
            
            Maj_sha256(a_bytes , b_bytes , c_bytes , result) ; 
            uint32_t T2 =  Sum0_256_sha256(a) + bytes_to_be(result)    ;  
            
            h = g ;
            
            g = f ; 
            
            f = e ; 
            
            e = d + T1 ; 
            
            d = c ; 
            
            c = b ;
            
            b = a ; 
            
            a = T1 + T2 ;

        }

        be_to_bytes( a  +  bytes_to_be(H + 0*4)  ,H + 0*4 ) ; 
        be_to_bytes( b  +  bytes_to_be(H + 1*4)  ,H + 1*4 ) ; 
        be_to_bytes( c  +  bytes_to_be(H + 2*4)  ,H + 2*4 ) ; 
        be_to_bytes( d  +  bytes_to_be(H + 3*4)  ,H + 3*4 ) ; 
        be_to_bytes( e  +  bytes_to_be(H + 4*4)  ,H + 4*4 ) ; 
        be_to_bytes( f  +  bytes_to_be(H + 5*4)  ,H + 5*4 ) ; 
        be_to_bytes( g  +  bytes_to_be(H + 6*4)  ,H + 6*4 ) ; 
        be_to_bytes( h  +  bytes_to_be(H + 7*4)  ,H + 7*4 ) ; 
        

        // break;
    }

    memcpy(digest , H , sizeof(uchar_t)*8*4) ; 


}

